pipeline {
    agent any

    environment {
        APP_NAME = "fastapi-app"
    }

    stages {

        stage('Clone Repository') {
            steps {
                git 'https://github.com/RohitPatil18/docker-fastapi-test.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker compose build'
            }
        }

        stage('Deploy Container') {
            steps {
                sh '''
                docker compose down || true
                docker compose up -d
                '''
            }
        }

        stage('Verify Running Containers') {
            steps {
                sh 'docker ps'
            }
        }
    }

    post {
        success {
            echo 'Deployment Successful!'
        }

        failure {
            echo 'Deployment Failed!'
        }
    }
}